### ISSUE TITLE
Remove branches which we do not use or want to see?

### ISSUE THREAD

**Issue by MichaelSchulzMETNO** [NorESMhub/cime#14]
Would it be possible to identify the banches which we are not using and remove them from the NorESMhub/cime fork?

**Comment by monsieuralok** [comment]
@MichaelSchulzMETNO @matsbn @tto061 @oyvindseland @huitang-earth I will remove following branches from cime. It would be nice if you can check once and if want to keep it up let me know. I will delete these following branches  on 1st October 2021. 

altuntas/MOM6_misomip
aws-tutorial
altuntas/MOM6_mct
cime4.2.3_cheyenne_port
cesm1_3_branch
gh-pages
cime5.6.16_pop2cism
theia_fix
jayeshkrishna/adios_support
dqwu/anlworkstation_pio1
dqwu/anlworkstation_pio2
rsdunlapiv/cmeps0.4branch
nems_integration
nems_integration_fixed
jgfouca/branch-for-acme-split-2019-11-15
global_workflow
fv3gfs_cime_build
fischer/izumi
maint-5.6
uturuncoglu/ufs_release
mvertens/refactor_dmodels_to_esmf
revert-3377-update_nuopc_esmf
mvertens/new_component_directories
mvertens/new_component_directories2
mvertens/new_component_directories3
master_cime

**Comment by MichaelSchulzMETNO** [comment]
Small suggestion: Could you also indicate which branches should be kept in the future?

**Comment by monsieuralok** [comment]
> 
> 
> Small suggestion: Could you also indicate which branches should be kept in the future?

@MichaelSchulzMETNO I have put list of branches that we will maintain temporary or long term.  But, it would need some discussion after cleaning up this repository. My present aim is to remove maximum unnecessary branches and then think about naming (as I discussed in last core meeting) and structures (I would soon discuss it in one core meeting).
