### ISSUE TITLE
Bug in seq_infodata_mod.F90

### ISSUE THREAD

**Issue by j34ni** [NorESMhub/cime#19]
At line 2904 replace F0**I** (which corresponds to "(2A,I10)") by F0**L** (which corresponds to "(2A,L3)") because alb_cosz_avg is defined as a logical and not an integer

**Comment by j34ni** [comment]
@cime-core: Is there anybody following this up?

**Comment by monsieuralok** [comment]
@j34ni Thanks a lot for finding it out. I have updated the code.
