### ISSUE TITLE
Create a new cime branch for "NorESM_LandSites_Platform"

### ISSUE THREAD

**Issue by huitang-earth** [NorESMhub/cime#20]
This issue is related to the issue [205](https://github.com/NorESMhub/NorESM/issues/205) in NorESM repository and issue [5](https://github.com/NorESMhub/CTSM/issues/5) in CTSM repository.

The new CIME branch will be used to keep the version of CIME that works with the most recent version of CTSM and related model component. But whether it works with the atmosphere and ocean model components of NorESM is not tested. 

The new CIME branch will also contain a lot of setup for running single-cell simulations over observation sites.

The configuration for running the model on different supercomputers (e.g., SAGA, FRAM) will be the same as the branch for running global NorESM simulation. 

The new CIME branch is ready at [my local repository](https://github.com/huitang-earth/cime/tree/cime_noresm_site_platform_test). I can make a pull request if we decide on the name of the new branch. 

What would be a proper name for the new CIME branch? @annefou, @kjetilaas, @sunnivin, @DirkOlivie, @matsbn, @MichaelSchulzMETNO

**Comment by monsieuralok** [comment]
@huitang-earth created branch NorESM_LandSites_Platform based on cime5.6.10_cesm2_1_rel_06-Nor
