### ISSUE TITLE
Workflows

### ISSUE THREAD

**Issue by mvdebolskiy** [NorESMhub/cime#63]
Port modifications that have been introduced to cime for NorESM 2.0  (zipping and long-term archiving) into the workflows in cime6 for the development version.

**Comment by gold2718** [comment]
@mvdebolskiy, Is this backporting some CIME6 functionality into the NorESM2 version of CIME?
Is this something you intend to do for the (imminent) NorESM2.1 release? The NorESM2.3 release? If so, please check the appropriate milestone.
