### ISSUE TITLE
Removing development branch "noresm2_1_develop"

### ISSUE THREAD

**Issue by TomasTorsvik** [NorESMhub/cime#85]
I would like to remove the branch `noresm2_1_develop` from the CIME repository.

The latest development of CIME for `noresm2.0.X`, `noresm2.1.X` and `noresm2.3.X` have been included on the `noresm2_3_develop` branch. These NorESM versions all share the same CIME tag (currently `cime5.6.10_NorESM2_3_r5`). The head of `noresm2_1_develop` is tagged as `cime5.6.10_NorESM2_3_r3`. There does not seem to be any reason to keep both `noresm2_1_develop` and `noresm2_3_develop` alive, and since the latest tags reference NorESM2_3_X I would like to keep only the latter of these branches.

If there are no objections, I propose to delete the `noresm2_1_develop` branch by the end of today. If someone should need it, the branch can be re-created from the tag `cime5.6.10_NorESM2_3_r3`.

**Comment by monsieuralok** [comment]
@TomasTorsvik Thanks for it, we should reduced branches; I do not have any problem; only we should check if this branch not pointing to any released tag.

**Comment by TomasTorsvik** [comment]
@monsieuralok - I have checked, and none of the NorESM releases points to this branch. `release-noresm2.1.1` points to the tag `cime5.6.10_NorESM2_1_r4`, but since `noresm2_3_develop` is a direct continuation of `noresm2_1_develop` there will not be any lost commits (the tags would be preserved in any case, I think).

**Comment by mvdebolskiy** [comment]
@TomasTorsvik is `cime5.6.10_NorESM2_3_r3` used anywhere? That one is on `noresm2_1_develop`

**Comment by TomasTorsvik** [comment]
@mvdebolskiy - `cime5.6.10_NorESM2_3_r3` was intended for `release-noresm2.0.8` and `release-noresm2.1.2`, but the `cprnc` tool was an old version, so we fixed this and made the `cime5.6.10_NorESM2_3_r4` tag. In any case, `cime5.6.10_NorESM2_3_r3` is also a tag on the `noresm2_3_develop` branch, because 2_1 and 2_3 were identical at that time.

**Comment by gold2718** [comment]
Because `cime5.6.10_NorESM2_3_r3` can be used at any time to re-create the noresm2_1_develop branch, I have removed the NorESMhub/noresm2_1_develop branch.
Note that if you use the `--prune` argument to your `git fetch` or `git pull` commands, it will remove this as a remote-tracking branch in your clone.
