### ISSUE TITLE
Add support for separate iHAMOCC test list

### ISSUE THREAD

**Issue by TomasTorsvik** [NorESMhub/cime#92]
@gold2718 , @mvertens - I would like to introduce a separate test file for iHAMOCC. To my understanding, this requires a change in the `config_files.xml` file.

**Comment by gold2718** [comment]
I'm not sure I understand. Can't you just introduce a new testlist name inside of `<blom>/cime_config/testdefs/testlist_blom.xml`? There are no restrictions on those names since you have to specify them on the `./create_test` command line.

**Comment by TomasTorsvik** [comment]
I close this one as well.
